/**
 * What each drum pack's own notes mean, read off the packs themselves.
 *
 * General MIDI names notes 35 to 81. Every sampled library hangs its own
 * articulations off numbers outside that and no two vendors agree, so a
 * pack's own notes are silent in jamin unless something says what they are.
 * Nobody publishes a table. The packs, however, write their key down in
 * their folder names, and this is that key read back.
 *
 * Generated by `scripts/pack_maps.py`, which is the honest part: every line
 * below carries the evidence it came from, and where there was no evidence
 * there is no line. A pack that names nothing is absent rather than guessed
 * at. Re-run it against a collection and it will say what it found.
 *
 * Matched on the pack's folder name, which is how these collections travel.
 * A library imported under a different name gets nothing from here, and the
 * per-library note table is still where somebody says so by hand.
 *
 * @see core/drumKits.js learnInbound, components/DrumLibraryNotes.vue
 */
export const PACK_NOTES = {
  "Asia": {
    /* 7 of its notes are outside General MIDI, 9.2% of everything it plays.
       Its own folders name 52% of them. */
    notes: {
      86: "woodBlockHigh", // folder names (100% agreed)
    },
  },
  "GM MIDI Pack [360,000 files]": {
    /* 45 of its notes are outside General MIDI, 1.3% of everything it plays.
       Its own folders name 80% of them. */
    notes: {
      4: "maracas", // folder names (100% agreed)
      5: "guiroLong", // folder names (100% agreed)
      9: "tomFloor", // folder names (100% agreed)
      17: "timbaleHigh", // folder names (100% agreed)
      27: "cowbell", // folder names (100% agreed)
      29: "crash2", // folder names (100% agreed)
      30: "ride", // folder names (100% agreed)
      32: "ride", // folder names (100% agreed)
      34: "cabasa", // folder names (100% agreed)
      90: "congaHigh", // folder names (100% agreed)
      91: "claves", // folder names (100% agreed)
      96: "cowbell", // folder names (100% agreed)
      99: "ride", // folder names (100% agreed)
      116: "timbaleHigh", // folder names (100% agreed)
    },
  },
  "Superior Drummer 2 Drum Midi [425,000 files]": {
    /* 79 of its notes are outside General MIDI, 8.0% of everything it plays.
       Its own folders name 31% of them. */
    notes: {
      17: "timbaleHigh", // folder names (100% agreed)
      25: "hatOpen", // folder names (100% agreed)
      28: "snare", // folder names (100% agreed)
      82: "cabasa", // folder names (100% agreed)
      90: "congaLow", // folder names (74% agreed)
      116: "tomFloor", // folder names (100% agreed)
      121: "maracas", // folder names (100% agreed)
      124: "cabasa", // folder names (100% agreed)
      125: "cabasa", // folder names (100% agreed)
      126: "cabasa", // folder names (100% agreed)
    },
  },
}

/**
 * The map for a pack, by the name it was imported under.
 *
 * Exact, then case-insensitive, then a pack whose name is contained in the
 * imported one -- these collections travel with their file counts stuck on
 * the end, so `Superior Drummer 2 Drum Midi [425,000 files]` has to find
 * `Superior Drummer 2 Drum Midi`.
 */
export function notesForPack(name) {
  if (!name) return null
  if (PACK_NOTES[name]) return PACK_NOTES[name].notes

  const want = String(name).toLowerCase()
  for (const [pack, one] of Object.entries(PACK_NOTES)) {
    const lower = pack.toLowerCase()
    if (lower === want || want.includes(lower) || lower.includes(want)) return one.notes
  }
  return null
}
